# Generated by Django 4.0.4 on 2022-04-21 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('carbohydrates', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('protein', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('fats', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
            ],
        ),
    ]
