# Generated by Django 4.0.4 on 2022-04-12 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='protien',
            new_name='protein',
        ),
    ]
